const constant = {
    ROLE: ['TEACHER', 'STUDENT'],
    BRANCH: ['CSE', 'ME', 'CIVIL', 'EC'],
    SEMESTER: ['sem 1', 'sem 2', 'sem 3', 'sem 4', 'sem 5', 'sem 6', 'sem 7', 'sem 8'],
    SUBJECT: [{ name: "ENGINEERING MATHEMATICS-III ", branch: 'CSE', semester: 'sem 3' },
    { name: "ANALOG AND DIGITAL ELECTRONICS ", branch: 'CSE', semester: 'sem 3' },
    { name: "DATA STRUCTURES AND APPLICATIONS ", branch: 'CSE', semester: 'sem 3' },
    { name: "COMPUTER ORGANIZATION ", branch: 'CSE', semester: 'sem 3' },
    { name: "UNIX AND SHELL PROGRAMMING", branch: 'CSE', semester: 'sem 3' },
    { name: "DISCRETE MATHEMATICAL STRUCTURES", branch: 'CSE', semester: 'sem 3' },
    { name: "ANALOG AND DIGITAL ELECTRONICS LABORATORY", branch: 'CSE', semester: 'sem 3' },
    { name: "DATA STRUCTURES LABORATORY", branch: 'CSE', semester: 'sem 3' },
    { name: "ENGINEERING MATHEMATICS-IV ", branch: 'CSE', semester: 'sem 4' },
    { name: "OBJECT ORIENTED CONCEPTS ", branch: 'CSE', semester: 'sem 4' },
    { name: "DESIGN AND ANALYSIS OF ALGORITHMS", branch: 'CSE', semester: 'sem 4' },
    { name: "MICROPROCESSORS AND MICROCONTROLLERS", branch: 'CSE', semester: 'sem 4' },
    { name: "SOFTWARE ENGINEERING ", branch: 'CSE', semester: 'sem 4' },
    { name: "DATA COMMUNICATION ", branch: 'CSE', semester: 'sem 4' },
    { name: "DESIGN AND ANALYSIS OF ALGORITHM LABORATORY ", branch: 'CSE', semester: 'sem 4' },
    { name: "MICROPROCESSOR AND MICROCONTROLLER LABORATORY ", branch: 'CSE', semester: 'sem 4' },
    { name: "COMPUTER NETWORKS ", branch: 'CSE', semester: 'sem 5' },
    { name: "DATABASE MANAGEMENT SYSTEM  ", branch: 'CSE', semester: 'sem 5' },
    { name: "AUTOMATA THEORY AND COMPUTABILITY ", branch: 'CSE', semester: 'sem 5' },
    { name: "OBJECT ORIENTED MODELING AND DESIGN  ", branch: 'CSE', semester: 'sem 5' },
    { name: "INTRODUCTION TO SOFTWARE TESTING ", branch: 'CSE', semester: 'sem 5' },
    { name: "ADVANCED JAVA AND J2EE  ", branch: 'CSE', semester: 'sem 5' },
    { name: "ADVANCED ALGORITHMS  ", branch: 'CSE', semester: 'sem 5' },
    { name: "PROGRAMMING IN JAVA ", branch: 'CSE', semester: 'sem 5' },
    { name: "ARTIFICIAL INTELLIGENCE  ", branch: 'CSE', semester: 'sem 5' },
    { name: "EMBEDDED SYSTEMS  ", branch: 'CSE', semester: 'sem 5' },
    { name: "DOT NET FRAMEWORK FOR APPLICATION DEVELOPMENT  ", branch: 'CSE', semester: 'sem 5' },
    { name: "CLOUD COMPUTING  ", branch: 'CSE', semester: 'sem 5' },
    { name: "COMPUTER NETWORK LABORATORY  ", branch: 'CSE', semester: 'sem 5' },
    { name: "DBMS LABORATORY WITH MINI PROJECT  ", branch: 'CSE', semester: 'sem 5' },
    { name: "CRYPTOGRAPHY, NETWORK SECURITY AND CYBER LAW ", branch: 'CSE', semester: 'sem 6' },
    { name: "COMPUTER GRAPHICS AND VISUALIZATION ", branch: 'CSE', semester: 'sem 6' },
    { name: "SYSTEM SOFTWARE AND COMPILER DESIGN", branch: 'CSE', semester: 'sem 6' },
    { name: "OPERATING SYSTEMS ", branch: 'CSE', semester: 'sem 6' },
    { name: "DATA MINING AND DATA WAREHOUSING ", branch: 'CSE', semester: 'sem 6' },
    { name: "SOFTWARE ARCHITECTURE AND DESIGN PATTERNS", branch: 'CSE', semester: 'sem 6' },
    { name: "OPERATIONS RESEARCH ", branch: 'CSE', semester: 'sem 6' },
    { name: "PYTHON APPLICATION PROGRAMMING", branch: 'CSE', semester: 'sem 6' },
    { name: "SYSTEM SOFTWARE AND OPERATING SYSTEM LABORATORY", branch: 'CSE', semester: 'sem 6' },
    { name: "COMPUTER GRAPHICS LABORATORY WITH MINI PROJECT", branch: 'CSE', semester: 'sem 6' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    { name: "", branch: 'CSE', semester: 'sem 7' },
    ],
    HTML_STATUS_CODE: { SUCCESS: 200, CREATED: 201, UNAUTHORIZED: 401, INVALID_DATA: 406, CONFLICT: 409, INTERNAL_ERROR: 500, BAD_REQUEST: 400, NOT_FOUND: 404 },
    MESSAGE: {
        STUDENT: {
            CREATED: 'Student Registered Successfully. login to continue. ',
        },
        TEACHER: {
            CREATED: 'Instructor Registered Successfully .login to continue.. ',
        },
        COMMON: {
            INTERNAL_ERROR: 'Something went wrong. Please try again later..',
            EMAIL_TAKEN: 'Account already exist with this email. please try another email'
        },
        LOGIN: {
            SUCCESS: 'login successfully',
            EMAIL_NOT_VALID: 'Email not exit.signup first',
            WRONG_PASSWORD: `INVALID PASSWORD.`,
            EMAIL_SUCCESS: 'OTP SENT SUCCESFULLY',
            EMAIL_FAILED: 'PLEASE ENTER REGISTERED EMAIL',
            PASSWORD_CHANGED: 'you have successfully changed your password.',
            PASSWORD_CHG_FAILED: 'Invalid otp.please try again.',

        },
        TOPIC: {
            SUCCESS: 'Data fetched successfully',
            INSERTED: 'File uploaded successfully',
            FAIL: "Something went wrong. Please try again later..",
            DELETE:"Deleted successfully",
            COMMENT:"success",
            LIKED:"Thank you ",
            DISLIKED:"Sorry"

        },
        BRANCH: {},
        SUBJECT: {},
        SEMESTER: {},
    },
    STATUS: {
        SUCCESS: 'Success',
        FAIL: 'Fail'
    }
}
module.exports = constant;
